/**
 * Generates supabase/seed.sql from the mock catalog in src/lib/data.
 * Run with: npm run db:seed:generate
 */
import { writeFileSync } from "node:fs";
import { join } from "node:path";
import { categories } from "../src/lib/data/categories";
import { products } from "../src/lib/data/products";

const q = (v: string) => `'${v.replace(/'/g, "''")}'`;
const textArray = (arr: string[]) => (arr.length ? `array[${arr.map(q).join(", ")}]::text[]` : "'{}'::text[]");
const json = (v: unknown) => `${q(JSON.stringify(v))}::jsonb`;

const lines: string[] = [
  "-- Generated by scripts/generate-seed.ts — do not edit by hand.",
  "begin;",
  "",
  "insert into public.categories (slug, name, description, image, sort_order) values",
  categories
    .map((c, i) => `  (${q(c.slug)}, ${q(c.name)}, ${q(c.description)}, ${q(c.image)}, ${i})`)
    .join(",\n") +
    "\non conflict (slug) do update set name = excluded.name, description = excluded.description, image = excluded.image, sort_order = excluded.sort_order;",
  "",
  "insert into public.products (id, slug, name, brand, category, price, compare_at_price, rating, review_count, stock, short_description, description, highlights, details, images, tags, created_at) values",
  products
    .map(
      (p) =>
        `  (${[
          q(p.id),
          q(p.slug),
          q(p.name),
          q(p.brand),
          q(p.category),
          p.price,
          p.compareAtPrice ?? "null",
          p.rating,
          p.reviewCount,
          p.stock,
          q(p.shortDescription),
          q(p.description),
          textArray(p.highlights),
          json(p.details),
          json(p.images),
          textArray(p.tags),
          q(p.createdAt),
        ].join(", ")})`,
    )
    .join(",\n") +
    `
on conflict (id) do update set
  slug = excluded.slug, name = excluded.name, brand = excluded.brand, category = excluded.category,
  price = excluded.price, compare_at_price = excluded.compare_at_price, rating = excluded.rating,
  review_count = excluded.review_count, stock = excluded.stock, short_description = excluded.short_description,
  description = excluded.description, highlights = excluded.highlights, details = excluded.details,
  images = excluded.images, tags = excluded.tags, created_at = excluded.created_at;`,
  "",
  "commit;",
  "",
];

const out = join(import.meta.dirname, "..", "supabase", "seed.sql");
writeFileSync(out, lines.join("\n"));
console.log(`Wrote ${categories.length} categories and ${products.length} products to ${out}`);
